classes: {
  *.label.near: bottom-center
  *.style.border-radius: 5
  *.style.fill: transparent

  title: {
    near: bottom-center
    shape: text
    style.font-size: 40
    style.underline: true
  }

  externalCloudService: {
    icon: https://icons.terrastruct.com/infra%2F022-hosting.svg
  }

  user: {
    icon: https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/svgs/regular/user.svg
  }

  aws: {
    label.near: bottom-left
    style: {
      stroke-dash: 10
      stroke: "#f4a261"
    }
  }

  vpc: {
    label.near: bottom-left
    style: {
      stroke-dash: 4
    }
  }

  apiGW: {
    icon: ../icons/apigw.svg}

  lambda: {
    icon: ../icons/lambda.svg
  }

  ECS: {
    icon: ../icons/ecs.svg }

  dynamo: {
    icon: ../icons/dynamo.svg
  }

  s3: {
    icon: ../icons/s3.svg
  }

  cloudfront: {
    icon: ../icons/cloudfront.svg
  }

  KMS: {
    icon: ../icons/KMS.svg
  }

  idpSPID: {
    shape: image
    icon: ../icons/spid-logo.svg
  }

  parameterStore {
    icon: ../icons/paramstore.svg }

  github {
    icon: ../icons/github.png
  }

  identityServices {
    icon: ../icons/pagopa.jpeg
  }
}