classes {
  *.label.near: bottom-center
  *.style.border-radius: 5
  *.style.fill: transparent

  title: {
    near: bottom-center
    shape: text
    style.font-size: 40
    style.underline: true
  }

  externalCloudService: {
    icon: https://icons.terrastruct.com/infra%2F022-hosting.svg
  }

  user: {
    icon: https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/svgs/regular/user.svg
  }

  aws: {
    label.near: bottom-center
    style: {
      stroke-dash: 10
      stroke: "#f4a261"
    }
  }

  vpc: {
    label.near: top-left
    style: {
      stroke-dash: 4
    }
  }

  apiGW {
    icon: https://raw.githubusercontent.com/weibeld/aws-icons-svg/main/q1-2022/Architecture-Service-Icons_01312022/Arch_App-Integration/Arch_32/Arch_%20Amazon-API-Gateway_32.svg
  }

  lambda: {
    icon: https://raw.githubusercontent.com/weibeld/aws-icons-svg/main/q1-2022/Architecture-Service-Icons_01312022/Arch_Compute/32/Arch_AWS-Lambda_32.svg

  }

  ECS: {
    icon: https://raw.githubusercontent.com/weibeld/aws-icons-svg/main/q1-2022/Architecture-Service-Icons_01312022/Arch_Compute/32/Arch_Amazon-Elastic-Container-Service_32.svg
  }

  dynamo: {
    icon: https://raw.githubusercontent.com/weibeld/aws-icons-svg/main/q1-2022/Architecture-Service-Icons_01312022/Arch_Database/32/Arch_Amazon-DynamoDB_32.svg
  }

  s3: {
    icon: https://raw.githubusercontent.com/weibeld/aws-icons-svg/main/q1-2022/Architecture-Service-Icons_01312022/Arch_Storage/32/Arch_Amazon-S3-on-Outposts_32.svg
  }

  cloudfront: {
    icon: https://raw.githubusercontent.com/weibeld/aws-icons-svg/main/q1-2022/Architecture-Service-Icons_01312022/Arch_Networking-Content-Delivery/32/Arch_Amazon-CloudFront_32.svg
  }

  KMS: {
    icon: https://raw.githubusercontent.com/weibeld/aws-icons-svg/main/q1-2022/Architecture-Service-Icons_01312022/Arch_Security-Identity-Compliance/32/Arch_AWS-Key-Management-Service_32.svg
  }

  idpSPID {
    shape: image
    icon: https://raw.githubusercontent.com/italia/spid-graphics/master/spid-logos/spid-logo-c-lb.svg
  }
}