config: {
    layout-engine: elk
    theme-overrides:{
      N1: "#4C566A"
      N2: "#4C566A"
      B1: "#5E81AC"
      B2: "#81A1C1"
      B3: "#81A1C1"
      B4: "#81A1C1"
      B5: "#81A1C1"
      B6: "#88C0D0"
    }
}