quarkus:
  dynamodb:
    devservices:
      enabled: 'false'
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] (%t) [%C.%M] %s%e%n"
'%dev':
  quarkus:
    dynamodb:
      aws:
        credentials:
          type: static
          static-provider:
            secret-access-key: testsecret
            access-key-id: testkey
        region: local
      endpoint-override: http://localhost:8000
'%prod':
  quarkus:
    dynamodb:
      aws:
        credentials:
          type: default
        region: eu-south-1

client_registrations_table_name: ${CLIENT_REGISTRATIONS_TABLE_NAME:ClientRegistrations}