quarkus.lambda.handler=cache-updater
quarkus.package.jar.type=uber-jar

#region Log
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p (%t) [%C.%M] %s%e%n
quarkus.log.handler.console.start-end-handler.format=%d{yyyy-MM-dd HH:mm:ss} %-5p (%t) %s%e%n
quarkus.log.category."it.pagopa.oneid.common.utils.logging".handlers=start-end-handler
quarkus.log.category."it.pagopa.oneid.common.utils.logging".use-parent-handlers=false
quarkus.log.category."it.pagopa.oneid".level=${LOG_LEVEL:INFO}
%dev.quarkus.log.category."it.pagopa.oneid".level=DEBUG
#endregion

#region Quarkus
quarkus.http.test-port=0
#endregion

quarkus.arc.exclude-types=it.pagopa.oneid.common.connector.ClientConnectorImpl,it.pagopa.oneid.common.connector.IDPConnectorImpl,it.pagopa.oneid.common.connector.LastIDPUsedConnectorImpl,it.pagopa.oneid.common.utils.SSMConnectorUtilsImpl,it.pagopa.oneid.common.utils.KmsUtilsImpl,it.pagopa.oneid.common.utils.config.ConfigBasicX509Credential,it.pagopa.oneid.common.utils.SAMLUtils
