name: plan
description: "Run terraform plan"

inputs:
  region: 
    required: true
    type: string
  working-directory:
    required: true
    type: string
  iam_role:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Read terraform version 
      id: read-version
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "TERRAFORM_VERSION=`cat ../../.terraform-version`" >> $GITHUB_ENV

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3
      with:
        role-to-assume: ${{ inputs.iam_role }}
        aws-region: ${{ inputs.region }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    
    - name: Terraform Format
      id: fmt
      shell: bash
      run: terraform fmt -check --recursive
      working-directory: ./src/infra


    - name: Terraform Init
      id: init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform init
    - name: Terraform Plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform plan -lock-timeout=60s
