#region Prod
## CloudWatch
%prod.quarkus.cloudwatch.aws.region=${AWS_REGION:eu-south-1}
%prod.quarkus.cloudwatch.aws.credentials.type=default
## S3
%prod.quarkus.s3.aws.region=${AWS_REGION:eu-south-1}
%prod.quarkus.s3.aws.credentials.type=default
#endregion
#region Dev
## CloudWatch
%dev.quarkus.cloudwatch.aws.region=us-east-1
%dev.quarkus.cloudwatch.aws.credentials.type=static
%dev.quarkus.cloudwatch.endpoint-override=http://localhost:4566
%dev.quarkus.cloudwatch.aws.credentials.static-provider.access-key-id=test
%dev.quarkus.cloudwatch.aws.credentials.static-provider.secret-access-key=test
## S3
%dev.quarkus.s3.aws.region=us-east-1
%dev.quarkus.s3.aws.credentials.type=static
%dev.quarkus.s3.endpoint-override=http://localhost:4566
%dev.quarkus.s3.aws.credentials.static-provider.access-key-id=test
%dev.quarkus.s3.aws.credentials.static-provider.secret-access-key=test
#endregion
quarkus.lambda.handler=client-publisher
quarkus.package.jar.type=uber-jar
#region Client Publisher
clients_bucket_name=${CLIENTS_BUCKET_NAME:test-clients-bucket}
clients_key_prefix=${CLIENTS_KEY_PREFIX:clients-publisher/}
global_clients_key=${GLOBAL_CLIENTS_KEY:clients.json}
client_registrations_table_name=${CLIENT_REGISTRATIONS_TABLE_NAME:ClientRegistrations}
cloudwatch_custom_metric_namespace=${CLOUDWATCH_CUSTOM_METRIC_NAMESPACE:TestNamespace}
#endregion
#region Log
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p (%t) [%C.%M] %s%e%n
quarkus.log.handler.console.start-end-handler.format=%d{yyyy-MM-dd HH:mm:ss} %-5p (%t) %s%e%n
quarkus.log.category."it.pagopa.oneid.common.utils.logging".handlers=start-end-handler
quarkus.log.category."it.pagopa.oneid.common.utils.logging".use-parent-handlers=false
quarkus.log.category."it.pagopa.oneid".level=${LOG_LEVEL:INFO}
%dev.quarkus.log.category."it.pagopa.oneid".level=DEBUG
#endregion
#region Quarkus
quarkus.http.test-port=0
## Quarkus dev services
quarkus.s3.devservices.enabled=false
quarkus.cloudwatch.devservices.enabled=false
#endregion
