name: Deploy IDP Service

on:
  push:
    branches:
      - "main"
    paths:
      - "**/src/hello-go/**"
      - "Dockerfile"
      - ".github/workflows/deploy-idp-yml"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        type: choice
        required: true
        default: dev
        options:
        - dev
jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
        matrix: ${{ steps.setmatrix.outputs.matrix }}

    steps:
      - name: Build
        run: >
          echo "TODO"

      - name: Set Dynamic Env Matrix
        id: setmatrix
        run: |
          if [ ${{ github.ref == 'refs/heads/main' }} == true ] && [ ${{ github.event_name != 'workflow_dispatch' }} == true ]; then
            matrixStringifiedObject="{\"include\":[{\"environment\":\"uat\", \"env_short\": \"u\"},{\"environment\":\"prod\", \"env_short\": \"p\"}]}"
          else
            matrixStringifiedObject="{\"include\":[{\"environment\":\"dev\", \"env_short\": \"d\"}]}"        
          fi
          echo "matrix=$matrixStringifiedObject" >> $GITHUB_OUTPUT          
      
  deploy:
    name: "Deploy on ECS"
    if: ${{ needs.build.outputs.matrix != '' }}
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    strategy:
        matrix: ${{ fromJson(needs.build.outputs.matrix) }}
         
    continue-on-error: false
    environment: ${{ matrix.environment }}
    env:
      AWS_REGION: eu-south-1

    steps:
      - uses: actions/checkout@v4
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.IAM_ROLE_DEPLOY_ECS }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
      
      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
          --task-definition pdv-${{ matrix.env_short }}-task-person \
          --query taskDefinition > ./task-definition.json
          echo $(cat ./task-definition.json | jq 'del(
                  .taskDefinitionArn,
                  .requiresAttributes,
                  .compatibilities,
                  .revision,
                  .status,
                  .registeredAt,
                  .registeredBy
              )') > ./task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1.2.0
        with:
          task-definition: ./task-definition.json
          container-name: idp
          image: ${{ steps.build-image.outputs.image }}

  #     - name: Deploy Amazon ECS task definition
  #       uses: aws-actions/amazon-ecs-deploy-task-definition@v1.4.11
  #       with:
  #         task-definition: ${{ steps.task-def.outputs.task-definition }}
  #         service: oneid-es-1-${{ matrix.env_short }}-ipd
  #         cluster: oneid-es-1-${{ matrix.env_short }}-ecs
  #         wait-for-service-stability: true

  # release:
  #   name: "Create Release"
  #   if: ${{ needs.build.outputs.matrix != '' }}
  #   needs: [build, deploy]
  #   runs-on: ubuntu-22.04
  #   strategy:
  #     matrix: ${{ fromJson(needs.build.outputs.matrix) }}
  #   environment: ${{ matrix.environment }}

  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Release
  #       if: ${{ matrix.environment == 'prod' }}
  #       id: release
  #       # from https://github.com/cycjimmy/semantic-release-action/commits/main
  #       uses: cycjimmy/semantic-release-action@v4.1.0
  #       with:
  #         semantic_version: 18.0.0
  #         extra_plugins: |
  #           @semantic-release/release-notes-generator@10.0.3
  #           @semantic-release/git@10.0.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}