name: OneID FE CI

on:
  push:
    branches:
      - "main"
      - "dev"
    paths:
      - "**/src/oneid/oneid-ecs-core/src/main/webui**"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run yarn install, lint and test
        working-directory: src/oneid/oneid-ecs-core/src/main/webui
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn test
      - name: List directory
        run: |
          ls -R src/oneid/oneid-ecs-core/
      - name: Archive build artifacts
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
          name: assets
          path: src/oneid/oneid-ecs-core/target/quinoa/build  
    
  # deploy:
  #     runs-on: ubuntu-22.04
  #     needs: build
  #     environment: dev
  #     permissions:
  #       id-token: write
  #       contents: read
  
  #     steps:
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e
  #       with:
  #         name: assets
  #         path: src/oneid/oneid-ecs-core/target/quinoa/build


  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
  #       with:
  #         role-to-assume: arn:aws:iam::471112878885:role/GitHubActionS3DeployRole
  #         aws-region: ${{ vars.AWS_REGION }}
   
  #     - name: Copy to S3
  #       run: |
  #           aws s3 sync src/oneid/oneid-ecs-core/target/quinoa/build s3://assets-6284