name: Terraform Plan

on:
  workflow_dispatch:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main
    paths:
      - 'src/infra/**'
      - '!src/infra/**/*.md'
    
defaults:
  run:
    shell: bash

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: "terraform-plan-${{ matrix.environment }}-${{ matrix.region }}"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: dev
            region: eu-south-1          
          - environment: uat
            region: eu-south-1
          - environment: prod
            region: eu-south-1          
          - environment: prod
            region: eu-central-1
          - environment: io-uat
            region: eu-south-1
            working_directory: src/infra/oneid-io/uat/eu-south-1
          - environment: io-prod/eu-south-1
            region: eu-south-1
            working_directory: src/infra/oneid-io/prod/eu-south-1
          # - environment: io-prod/eu-central-1
          #   region: eu-central-1
          #   working_directory: src/infra/oneid-io/prod/eu-central-1

    environment: ${{ matrix.environment == 'prod' && format('{0}/{1}', matrix.environment, matrix.region) || matrix.environment }}
    
    env:
      WORKING_DIR: ${{ matrix.working_directory || format('src/infra/{0}/{1}', matrix.environment, matrix.region) }}
      AWS_REGION: ${{ matrix.region }}
     
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7 https://github.com/actions/checkout/releases/tag/v4.1.7

      - name: Plan
        uses: ./.github/workflows/plan
        with:
          working-directory: ${{ env.WORKING_DIR }}
          region: ${{ matrix.region }}
          iam_role: ${{ vars.IAM_ROLE_IAC_PLAN }}
