name: Terraform Apply

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'src/infra/**'

defaults:
  run:
    shell: bash

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: "terraform-apply-${{ matrix.environment }}"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        environment: [dev, uat]
    environment: ${{ matrix.environment }}
    
    env:
      WORKING_DIR: src/infra/${{ matrix.environment }}/eu-south-1
      AWS_REGION: eu-south-1

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Apply
        uses: ./.github/workflows/apply
        with:
          working-directory: ${{ env.WORKING_DIR }}
          region: ${{ env.AWS_REGION }}
          iam_role: ${{ vars.IAM_ROLE_IAC }}
