name: Terraform Apply Regional

on:
  push:
    branches:
      - main
    paths:
      - 'src/infra/main/**'
      - '.github/workflows/terraform-apply-main.yml'
defaults:
  run:
    shell: bash
    working-directory: src/infra/main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    strategy:
      matrix:
        environment: [dev]
        region: ["eu-south-1"]        
        # include:
        #  - environment: prod
        #    region: eu-central-1
                    
    name: "terraform-apply"
    runs-on: ubuntu-22.04
    environment: ${{ matrix.environment }}
     
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ${{ matrix.region }}
      
      - name: Apply
        uses: ./.github/workflows/apply
        with:
          env: ${{ matrix.environment }}
          working-directory: src/infra/main
          region: ${{ matrix.region }}
  