name: Terraform Plan Dev
on:
  workflow_dispatch:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'     # excludes main
    paths:
      - 'src/infra/dev/**'
      - 'src/infra/modules/**'
defaults:
  run:
    shell: bash
    working-directory: src/infra/dev

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
                    
    name: "terraform-plan"
    runs-on: ubuntu-22.04
    environment: dev
     
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Plan
        uses: ./.github/workflows/plan
        with:
          working-directory: src/infra/dev
          region: ${{ vars.AWS_REGION }}
          iam_role: ${{ vars.IAM_ROLE_IAC }}
  