name: Terraform Apply Dev
on:
  workflow_dispatch:
  push:
    branches:
      - main     # runs only on the main branch.
    paths:
      - 'src/infra/dev/**'
      - 'src/infra/modules/**'
defaults:
  run:
    shell: bash
    working-directory: src/infra/dev

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
                    
    name: "terraform-apply"
    runs-on: ubuntu-22.04
    environment: dev
     
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Apply
        uses: ./.github/workflows/apply
        with:
          working-directory: src/infra/dev
          region: ${{ vars.AWS_REGION }}
          iam_role: ${{ vars.IAM_ROLE }}
  