name: Test FE

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "**/src/oneid/oneid-fe**"

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2 https://github.com/actions/checkout/releases/tag/v6.0.2
      - name: Use Node.js 24.x
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0 https://github.com/actions/setup-node/releases/tag/v6.4.0
        with:
          node-version: 24.x
      - name: Run yarn install, lint and test
        working-directory: src/oneid/oneid-fe
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn test:coverage
